version: '3'
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=bookworm
    ports:
      - '27017:27017'
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
